### ISSUE TITLE
events don't show in UI

### ISSUE THREAD

**Issue by sbe-arg** [falcosecurity/falcosidekick-ui#124]
on docker compose I can't figure out the way to see the sidekick events.
documentation improvements needed for new starters.

my falco.yaml settings

```
buffered_outputs: false
file_output:
  enabled: false
  filename: ./events.txt
  keep_alive: false
grpc:
  bind_address: unix:///run/falco/falco.sock
  enabled: false
  threadiness: 0
grpc_output:
  enabled: false

http_output:
  enabled: true
  url: "http://falcosidekick:2801/"
json_include_output_property: true
json_output: true

libs_logger:
  enabled: false
  severity: debug
load_plugins: []
log_level: info
log_stderr: true
log_syslog: true
metadata_download:
  chunk_wait_us: 1000
  max_mb: 100
  watch_freq_sec: 1
modern_bpf:
  cpus_for_each_syscall_buffer: 2
output_timeout: 2000
outputs:
  max_burst: 1000
  rate: 1
plugins:
  - init_config: null
    library_path: libk8saudit.so
    name: k8saudit
    open_params: http://:9765/k8s-audit
  - library_path: libcloudtrail.so
    name: cloudtrail
  - init_config: ''
    library_path: libjson.so
    name: json
priority: debug
program_output:
  enabled: false
rules_file:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d
stdout_output:
  enabled: true
syscall_buf_size_preset: 4
syscall_event_drops:
  actions:
    - log
    - alert
  max_burst: 1
  rate: 0.03333
  simulate_drops: false
  threshold: 0.1
syscall_event_timeouts:
  max_consecutives: 1000
syslog_output:
  enabled: true
time_format_iso_8601: false
watch_config_files: true

webserver:
  enabled: true
  k8s_healthz_endpoint: /healthz
  listen_port: 8765
  ssl_enabled: false
  threadiness: 0
```

my compose.yaml
```
  falco:
    image: falcosecurity/falco:latest
    ports:
      - 8765:8765
    volumes:
      - ./falco.yaml:/etc/falco/falco.yaml
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro 
      - /etc:/host/etc:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
    privileged: true

  falcosidekick:
    image: falcosecurity/falcosidekick:latest
    ports:
      - 2801:2801
    environment:
      - REDIS_ADDRESS=falcoredis:6379

  falcoredis:
    image: redislabs/redisearch:2.2.4
    ports:
      - 6379:6379

  falcosidekick-ui:
    image: falcosecurity/falcosidekick-ui:latest
    ports:
       - 2802:2802
    depends_on:
      - falcoredis
    environment:
      - FALCOSIDEKICK_UI_REDIS_URL=falcoredis:6379
      - FALCOSIDEKICK_UI_USER=admin:admin
      - FALCOSIDEKICK_UI_DISABLEAUTH=false
```

running events

```
sudo docker run -it --rm falcosecurity/event-generator run
```

events are logged in falco, sent notifications via sidekick but nothing shows on sidekick-ui
I'm doing something wrong?

my sidekick-ui logs

```
services-falcosidekick-ui-1  | 2023/10/10 13:12:39 [WARN] : Index does not exist
services-falcosidekick-ui-1  | 2023/10/10 13:12:39 [WARN] : Create Index
services-falcosidekick-ui-1  | 2023/10/10 13:12:39 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
services-falcosidekick-ui-1  | 2023/10/10 13:12:39 [INFO] : Log level is info
services-falcosidekick-ui-1  | 2023/10/10 19:24:17 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
services-falcosidekick-ui-1  | 2023/10/10 19:24:17 [INFO] : Log level is info
services-falcosidekick-ui-1  | 2023/10/10 19:24:36 [INFO] : user 'admin' authenticated
services-falcosidekick-ui-1  | 2023/10/10 19:25:15 [INFO] : Falcosidekick UI is listening on 0.0.0.0:2802
services-falcosidekick-ui-1  | 2023/10/10 19:25:15 [INFO] : Log level is info
```

![image](https://github.com/falcosecurity/falcosidekick-ui/assets/23391642/1b1243b4-13cc-470e-9260-a8b466cc476a)
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/23391642/3d4ee53c-ded4-4b2d-aab5-3f9fe9927c3f)
