### ISSUE TITLE
No data is displayed in falcosidekick-ui website

### ISSUE THREAD

**Issue by amgonzalezf** [falcosecurity/falcosidekick-ui#133]
I installed falcosidekick with falcosidekick-ui enabled but I don't see any data in the UI. I installed falco, falcosidekick and falcosidekick-ui with their helm charts.

**Steps to reproduce:**

1. Install the version 3.8.7 of the helm chart of falco with these values:
```yaml
driver:
  kind: modern-bpf
tty: true
falcoctl:
  config:
    artifact:
      install:
        refs: [falco-rules:2, k8saudit-rules:0.6]
      follow:
        refs: [falco-rules:2, k8saudit-rules:0.6]
services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765
        nodePort: 30007
        protocol: TCP
falco:
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  load_plugins: [k8saudit, json]
  ```

2. Install the version 0.7.11 of the helm chart of falcosidekick with these values:
```yaml
webui:
  enabled: true
  user: "test:test"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-http
      kubernetes.io/ingress.class: nginx
    hosts:
    - host: falco.test.de
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - falco.test.de
      secretName: falco-tls
```
**Expected behaviour:**
After the installation of the components,  data should be visible in falcosidekick-ui. I can see events happening in the logs of the pods of falco, but I can't see them in the website of falcosidekick-ui

**Screenshots**
![image](https://github.com/falcosecurity/falcosidekick-ui/assets/131769676/6d1b21df-6928-4124-bbf3-24fec6fac3be)

**Versions:**
- Falco: 0.36.2
- Falcosidekick: 2.28.0
- Falcosidekick-ui: 2.2.0

**Comment by Issif** [comment]
Hi,

To install the whole stack, you have 2 choices:
* installing the falco helm chart + installing the falcosidekick helm chart aside
	* it requires you to set up by your own the falco `http output` to send the events to the falcosidekick service
* installing the falco helm chart and just enabling the falcosidekick dependency
   * it will set up for you the `http_output`

The easiest way is to install the falco chart only with the setting to enable sidekick. 

Here's the values.yaml with your config:


```yaml
driver:
  kind: modern-bpf
tty: true
falcoctl:
  config:
    artifact:
      install:
        refs: [falco-rules:2, k8saudit-rules:0.6]
      follow:
        refs: [falco-rules:2, k8saudit-rules:0.6]
services:
  - name: k8saudit-webhook
    type: NodePort
    ports:
      - port: 9765
        nodePort: 30007
        protocol: TCP
falco:
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/k8s_audit_rules.yaml
    - /etc/falco/rules.d
  load_plugins: [k8saudit, json]

falcosidekick:
  enabled: true
  webui:
    enabled: true
    user: "test:test"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http
        kubernetes.io/ingress.class: nginx
      hosts:
      - host: falco.test.de
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - falco.test.de
        secretName: falco-tls
```
