### ISSUE TITLE
Control the memory consumption of Redis Stack

### ISSUE THREAD

**Issue by iohenkies** [falcosecurity/falcosidekick-ui#140]
On Kubernetes, using Falco, Falcosidekick and Falcosidekick UI with the Redis instance that comes with it, we're looking for a way to control Redis memory usage. Because usage seems to grow and grow until the Redis pod gets OOM killed over and over again.

This is the used Redis config:

```
    redis:
      enabled: true
      image:
        pullPolicy: IfNotPresent
        registry: docker.io
        repository: redis/redis-stack
        tag: "7.2.0-v8"
      storageEnabled: true
      storageSize: "20Gi"
      storageClass: ""
      resources:
        requests:
          cpu: 500m
          memory: 1024Mi
        limits:
          cpu: 2000m
          memory: 4096Mi
```

And I believe the `ttl` setting below should rotate data:

```
  webui:
    enabled: true
    replicaCount: 2
    ttl: 7d
```

It is unclear what Redis does with this setting. It would be useful to be able to set settings like the below, which should probably prevent these issues:

```
maxmemory-policy allkeys-lfu
maxmemory 4096mb
```

I hope there is a way to keep it manageable without increasing the memory limit and decreasing the `ttl`.
