### ISSUE TITLE
Base path configuration

### ISSUE THREAD

**Issue by mxmdt3** [falcosecurity/falcosidekick-ui#157]
Is it possible to add support for a configurable base path ? I cannot use falcosidekick-ui without it in my kubernetes cluster.

**Comment by prashant0085** [comment]
Even I can't use falco when trying to configure it at a path. I use istio and when I try to configure virtual service, it doesn't works and times out:

isito config with falco path:
```
internalVS:
  enabled: true
  fqdn: example.com
  svc:
    - name: falco-falcosidekick-ui
      path: /falco
      port: 2802

```
`example.com/falco` doesn't work

but when I configure with path like below it works:
```
internalVS:
  enabled: true
  fqdn: example.com
  svc:
    - name: falco-falcosidekick-ui
      path: /
      port: 2802
```
falco is accessible via `example.com/`
