### ISSUE TITLE
Blank charts in falcosidekick-ui but falco is working

### ISSUE THREAD

**Issue by anthares101** [falcosecurity/falcosidekick-ui#95]
**Describe the bug**

The falcosidekick-ui is showing blank charts, I can see that in the top it is reporting the events though. Also, I can see that events are appearing in the Falco logs.

**How to reproduce it**

The installation command:
````bash
helm install falco falcosecurity/falco --namespace falco --create-na
mespace --values values.yaml
````

My values file:
````yaml
driver:
  kind: ebpf

falcosidekick:
  enabled: true
  replicaCount: 1
  webui:
    enabled: true
    replicaCount: 1
    user: "REDACTED"
    ingress:
      enabled: true
      hosts:
      - host: falco.magi.lan
        paths:
        - path: /
      tls:
      - hosts:
        - falco.magi.lan

  config:
    customfields: "cluster:MAGI"

tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
- key: CriticalAddonsOnly
  operator: Exists
  effect: NoSchedule
````

**Expected behaviour**

The UI charts should be populated with falco events.

**Screenshots**

![image](https://user-images.githubusercontent.com/33127189/229712457-f4914cb2-b6bd-4832-bbf7-17253d7a36a0.png)
![image](https://user-images.githubusercontent.com/33127189/229712543-a2963568-d5ef-4b44-9509-e8c94dae3747.png)

**Environment**

- Falco version:
Falco version: 0.34.1 (aarch64)
- System info:
````json
{
  "machine": "aarch64",
  "nodename": "falco-6s564",
  "release": "6.1.19-v8+",
  "sysname": "Linux",
  "version": "#1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023"
}
````
- Cloud provider or hardware configuration:
3 nodes K3S cluster, the nodes are raspberry pi 4 b with 4GB of RAM each.
- OS:
Debian GNU/Linux 11 (raspbian bullseye)
- Kernel:
Linux 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
- Installation method:
Falco Helm chart
